#!/usr/bin/env python

from app import chinese_phrase_graph

chinese_phrase_graph.add_phrase("口", meaning="mouth")
chinese_phrase_graph.add_phrase("吃饭", meaning="to eat food")
chinese_phrase_graph.add_phrase("喝", meaning="to drink")
chinese_phrase_graph.add_phrase("咬", meaning="to bite")
chinese_phrase_graph.add_phrase("喵", meaning="to meow, like a cat")
chinese_phrase_graph.add_phrase("猫", meaning="cat")
chinese_phrase_graph.add_phrase("狗", meaning="dog")
chinese_phrase_graph.add_phrase("渴", meaning="thirsty")
chinese_phrase_graph.add_phrase("你好", meaning="hello")
chinese_phrase_graph.add_phrase("您好", meaning="hello, but polite you")
chinese_phrase_graph.add_phrase("高兴", meaning="happy")
chinese_phrase_graph.add_phrase("早", meaning="sunrise")
chinese_phrase_graph.add_phrase("旦", meaning="early morning")
chinese_phrase_graph.add_phrase("日", meaning="sun")
chinese_phrase_graph.add_phrase("日本", meaning="Japan")
chinese_phrase_graph.add_phrase("好久不见", meaning="long time no see")
chinese_phrase_graph.add_phrase("再见", meaning="goodbye")
chinese_phrase_graph.add_phrase("见", meaning="to see")
chinese_phrase_graph.add_phrase("你怎么样", meaning="how are you doing?")
chinese_phrase_graph.add_phrase("什么", meaning="what?")
chinese_phrase_graph.add_phrase("最近", meaning="recently")

chinese_phrase_graph.connect_phrases("口", "吃饭", note="Look at the 口 radical")
chinese_phrase_graph.connect_phrases("口", "喝")
chinese_phrase_graph.connect_phrases("口", "咬")
chinese_phrase_graph.connect_phrases("口", "喵")
chinese_phrase_graph.connect_phrases("猫", "喵")
chinese_phrase_graph.connect_phrases("猫", "狗", note="Notice the matching radical!")
chinese_phrase_graph.connect_phrases("喝", "渴")
chinese_phrase_graph.connect_phrases("你好", "您好")
chinese_phrase_graph.connect_phrases("早", "旦")
chinese_phrase_graph.connect_phrases("早", "日")
chinese_phrase_graph.connect_phrases("日", "旦")
chinese_phrase_graph.connect_phrases("日", "日本")
chinese_phrase_graph.connect_phrases("再见", "见")
chinese_phrase_graph.connect_phrases("好久不见", "见")
chinese_phrase_graph.connect_phrases("你怎么样", "什么")
